version: "3.8"

services:
  django-app:
    build: .
    command:
      - sh
      - -c
      - |
        python manage.py makemigrations
        python manage.py migrate --noinput
        gunicorn --bind :8000 --workers 3 -t 60 robot_app.wsgi:application
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - database
    env_file:
      - .env
    networks:
      - broker_network
      - nginx_network
      - database_network

  database:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=robot
      - POSTGRES_PASSWORD=robot
      - POSTGRES_DB=robot
    networks:
      - database_network

  broker:
    image: redis:6.0.4-alpine
    networks:
      - broker_network
    volumes:
      - broker_data:/data

  celery_worker:
    build: .
    command: celery -A robot_app worker
    restart: always
    depends_on:
      - database
      - broker
    env_file:
      - .env
    networks:
      - broker_network

  celery_beat:
    build: .
    command: celery -A robot_app beat
    restart: always
    depends_on:
      - database
      - broker
    env_file:
      - .env
    networks:
      - broker_network


  nginx:
    image: nginx
    ports:
      - "80:80"
    networks:
      - nginx_network
    depends_on:
      - django-app

networks:
  broker_network:
    name: broker_network
    driver: bridge
  nginx_network:
    name: nginx_network
    driver: bridge
  database_network:
    name: database_network
    driver: bridge

volumes:
  postgres_data:
  broker_data: